### ISSUE TITLE
Last check digit never gets used

### ISSUE THREAD

**Issue by chilts** [grantm/Algorithm-CouponCode#1]
Just wanted to loop you in here, since I think this project is also affected: https://github.com/chilts/node-coupon-code/issues/8

The 31, in `_checkdigit_alg_1` should be 32 : https://github.com/grantm/Algorithm-CouponCode/blob/master/lib/Algorithm/CouponCode.pm#L132 (or perhaps `scalar(@sym)`).

```
return $sym[ $check % 31 ];
```

Now, the question is, is it too much hassle to change assuming people have codes out in the wild, or do we fix it to be correct?

**Comment by grantm** [comment]
Closed as per my comment on the original issue report.

**Comment by chilts** [comment]
Cool, thanks Grant. :)
